---
name: latex
on:
  - push
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: compile resume in latex
        uses: xu-cheng/latex-action@v2
        with:
          latexmk_use_xelatex: true
          root_file: main.tex
