---
name: latex
on:
  push:
    paths:
      - .github/workflows/latex.yaml
      - '**.tex'
      - latexmk
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: compile resume in latex
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: main.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
