---
name: latex
on:
  push:
    paths:
      - .github/workflows/latex.yaml
      - '**.tex'
      - latexmk
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wtfjoke/setup-tectonic@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: compile resume in latex
        run: tectonic -X build
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/parham/parham.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
